import Head from 'next/head';
import Image from 'next/image';
import homeStyles from '../styles/Home.module.css';
import Link from 'next/link';
import Date from '../components/date';
import profilePic from '../public/images/profile.jpg';
import nextJsLogo from '../public/images/nextJs.svg';
import Alert from '../components/alert';
// Lib
import { getSortedPostsData } from '../lib/posts';

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export interface IProps {
  allPostsData: {
    id: string;
    title: string;
    date: string;
  }[];
}

const Home: React.FC<IProps> = ({ allPostsData }) => {
  // console.log('homepage.allPostsData', allPostsData);

  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h2 className='text-6xl mb-10 font-bold'>
        NextJS Concepts <span className='text-blue-600'>Blog</span>
      </h2>
      <ul className='flex flex-wrap justify-start w-full m-0 p-0'>
        {allPostsData.map(({ id, date, title }) => (
          <li
            className='list-none bg-white m-2 shadow-md p-5 rounded-xl w-full lg:w-1/4 hover:bg-gray-200'
            key={id}
          >
            <Link href={`/posts/${id}`}>
              <a className='text-blue-600 font-bold text-2xl'>{title}</a>
            </Link>
            <br />
            <small>
              <Date dateString={date} />
            </small>
          </li>
        ))}
      </ul>
    </>
  );
};

export default Home;
