import Head from 'next/head';
import Image from 'next/image';
import homeStyles from '../styles/Home.module.css';
import Link from 'next/link';
import profilePic from '../public/images/profile.jpg';
import Alert from '../components/alert';

export default function Home() {
  return (
    <div className='w-screen h-screen flex justify-center items-center'>
      <Head>
        <title>Next Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='text-center p-24'>
        <div className='flex flex-col justify-center items-center'>
          <Image
            src={profilePic}
            alt='profile pic'
            className='rounded-full'
            height={200}
            width={200}
          />
          <Link href='https://github.com/jleomorris'>
            <a className='mt-2'>@www.github.com/jleomorris</a>
          </Link>
        </div>
        <h1 className='mt-6 text-4xl font-extrabold'>James Morris</h1>
        <h2 className='text-2xl'>
          React Developer at IronmongeryDirect, Essex
        </h2>
        <div className='my-10 text-left'>
          <p className='text-2xl font-bold'>Blogs</p>
          <p className='text-2xl font-thin'>
            Read the{' '}
            <a href='/posts/first-post' className='text-purple-500'>
              first blog
            </a>
          </p>
        </div>
      </main>
    </div>
  );
}
